import { CardInList, ListType } from '@/types/magic';

const LIST_LABELS: Record<ListType, string> = {
  collection: 'Colección',
  'for-sale': 'En Venta',
  wishlist: 'Wishlist',
};

export function exportToCSV(cards: CardInList[], listType: ListType): void {
  const headers = ['Nombre', 'Set', 'Rareza', 'Cantidad', 'Precio (USD)', 'Notas', 'Fecha'];
  const rows = cards.map((card) => [
    card.cardName,
    card.setName,
    card.setRarity,
    String(card.quantity || 1),
    card.price ? card.price.toFixed(2) : '0.00',
    card.notes || '',
    card.addedAt ? new Date(card.addedAt).toLocaleDateString() : '',
  ]);

  const totalQty = cards.reduce((sum, c) => sum + (c.quantity || 1), 0);
  const totalValue = cards.reduce((sum, c) => sum + (c.price || 0) * (c.quantity || 1), 0);

  rows.push([]);
  rows.push(['Total Cartas', '', '', String(totalQty), totalValue.toFixed(2), '', '']);

  const csvContent = [
    headers.join(','),
    ...rows.map((row) =>
      row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(',')
    ),
  ].join('\n');

  const blob = new Blob(['\ufeff' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `magic_${listType}_${new Date().toISOString().split('T')[0]}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}

export async function exportToPDF(cards: CardInList[], listType: ListType): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = margin;

  const red = [46, 10, 10] as [number, number, number];
  const gold = [212, 175, 55] as [number, number, number];
  const white = [255, 255, 255] as [number, number, number];

  // Header
  doc.setFillColor(...red);
  doc.rect(0, 0, pageWidth, 25, 'F');
  doc.setFillColor(...gold);
  doc.rect(0, 25, pageWidth, 2, 'F');

  doc.setTextColor(...white);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`MTG ${LIST_LABELS[listType]}`, pageWidth / 2, 16, { align: 'center' });

  y = 35;

  // Summary
  const totalQty = cards.reduce((sum, c) => sum + (c.quantity || 1), 0);
  const totalValue = cards.reduce((sum, c) => sum + (c.price || 0) * (c.quantity || 1), 0);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total: ${totalQty} cartas | Valor: $${totalValue.toFixed(2)} USD`, margin, y);
  doc.text(`Exportado: ${new Date().toLocaleDateString()}`, pageWidth - margin, y, { align: 'right' });
  y += 8;

  // Table header
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y - 3, pageWidth - margin * 2, 6, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('Nombre', margin + 2, y);
  doc.text('Set', margin + 75, y);
  doc.text('Cant.', margin + 125, y);
  doc.text('Precio', margin + 145, y);
  y += 6;

  // Cards
  doc.setFont('helvetica', 'normal');
  const sorted = [...cards].sort((a, b) => a.cardName.localeCompare(b.cardName));

  for (const card of sorted) {
    if (y > 260) {
      doc.addPage();
      y = margin;
    }

    doc.text(card.cardName.substring(0, 40), margin + 2, y);
    doc.text((card.setName || '').substring(0, 25), margin + 75, y);
    doc.text(String(card.quantity || 1), margin + 125, y);
    doc.text(card.price ? `$${card.price.toFixed(2)}` : '-', margin + 145, y);
    y += 4;
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFillColor(...red);
  doc.rect(0, footerY - 2, pageWidth, 15, 'F');
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(6);
  doc.text('Generated by avsolem.com/magic', pageWidth / 2, footerY + 3, { align: 'center' });

  doc.save(`magic_${listType}_${new Date().toISOString().split('T')[0]}.pdf`);
}
