import type { AsciiTemplate } from './types';

const phos = '#7CFF6B';
const dim = 'rgba(124, 255, 107, 0.6)';
const bg = '#040806';

export const consoleTemplate: AsciiTemplate = {
  id: 'console-broadcast',
  name: 'Console Broadcast',
  category: 'terminal',
  ascii: {
    charset: 'standard',
    cols: 180,
    dither: 'bayer8',
    ditherSteps: 4,
    invertMapping: false,
    brightness: -0.1,
    contrast: 0.4,
    colorMode: 'mono',
    bgColor: bg,
    fgColor: phos,
    fontFamily: 'var(--font-code), ui-monospace, monospace',
    fontSizeRatio: 1.3,
    lineHeight: 1,
    letterSpacing: 0,
    cellOpacity: 0.9,
  },
  layout: {
    ratio: '16:9',
    bg,
    layers: [
      {
        id: 'header-l',
        text: '> BROADCAST_ID 0xA77F',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          top: '20px',
          left: '24px',
          fontSize: '11px',
          letterSpacing: '0.18em',
          color: phos,
          fontFamily: 'var(--font-code), monospace',
        },
      },
      {
        id: 'header-r',
        text: 'SIGNAL ▮▮▮▮▮▯▯',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          top: '20px',
          right: '24px',
          fontSize: '11px',
          letterSpacing: '0.18em',
          color: phos,
          fontFamily: 'var(--font-code), monospace',
        },
      },
      {
        id: 'title',
        text: '// PHOSPHOR //',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          fontFamily: 'var(--font-code), monospace',
          fontWeight: 700,
          fontSize: 'clamp(36px, 7vw, 96px)',
          color: phos,
          letterSpacing: '0.04em',
          textShadow: '0 0 16px rgba(124,255,107,0.45)',
        },
      },
      {
        id: 'sub',
        text: 'AUTHENTICATING TRANSMISSION ...',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, calc(-50% + 4rem))',
          fontFamily: 'var(--font-code), monospace',
          fontSize: '11px',
          letterSpacing: '0.3em',
          color: dim,
        },
      },
      {
        id: 'footer-l',
        text: '[F1] DECODE  [F2] LOOP  [ESC] ABORT',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          bottom: '20px',
          left: '24px',
          fontSize: '10px',
          letterSpacing: '0.2em',
          color: dim,
          fontFamily: 'var(--font-code), monospace',
        },
      },
      {
        id: 'footer-r',
        text: 'CH 04 · 11.4 KHz',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          bottom: '20px',
          right: '24px',
          fontSize: '10px',
          letterSpacing: '0.2em',
          color: dim,
          fontFamily: 'var(--font-code), monospace',
        },
      },
    ],
  },
};
