import type { AsciiTemplate } from './types';

const ink = '#1a1410';
const cream = '#f5ede0';
const accent = '#c44a1f';

export const solarTemplate: AsciiTemplate = {
  id: 'solar-bulletin',
  name: 'Solar Bulletin',
  category: 'editorial',
  ascii: {
    charset: 'sparse',
    cols: 140,
    dither: 'bayer4',
    ditherSteps: 5,
    invertMapping: true,
    brightness: 0.05,
    contrast: 0.2,
    colorMode: 'mono',
    bgColor: cream,
    fgColor: ink,
    fontFamily: 'var(--font-code), ui-monospace, monospace',
    fontSizeRatio: 1.4,
    lineHeight: 1,
    letterSpacing: 0,
    cellOpacity: 0.7,
  },
  layout: {
    ratio: '16:9',
    bg: cream,
    layers: [
      {
        id: 'eyebrow',
        text: 'BULLETIN · ISSUE 12 · SOLAR',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          top: '24px',
          left: '32px',
          right: '32px',
          fontSize: '10px',
          letterSpacing: '0.4em',
          color: accent,
          fontFamily: 'var(--font-code), monospace',
          textAlign: 'center',
          textTransform: 'uppercase',
        },
      },
      {
        id: 'title',
        text: 'Heliotype',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          fontFamily: 'var(--font-aurelia-display), serif',
          fontStyle: 'normal',
          fontWeight: 600,
          fontSize: 'clamp(56px, 11vw, 180px)',
          lineHeight: 1,
          color: ink,
          letterSpacing: '-0.03em',
          whiteSpace: 'nowrap',
        },
      },
      {
        id: 'caption',
        text: 'A new sun-warmed serif, drawn for slow reading.',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          bottom: '64px',
          left: '50%',
          transform: 'translateX(-50%)',
          fontSize: '12px',
          color: ink,
          fontFamily: 'var(--font-aurelia-display), serif',
          fontStyle: 'italic',
        },
      },
      {
        id: 'meta',
        text: '— TYPESTUDIO ARCHIVE',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          bottom: '24px',
          left: '32px',
          fontSize: '10px',
          letterSpacing: '0.3em',
          color: accent,
          fontFamily: 'var(--font-code), monospace',
        },
      },
      {
        id: 'page',
        text: 'P. 042',
        editable: true,
        className: '',
        style: {
          position: 'absolute',
          bottom: '24px',
          right: '32px',
          fontSize: '10px',
          letterSpacing: '0.3em',
          color: accent,
          fontFamily: 'var(--font-code), monospace',
        },
      },
    ],
  },
};
